; PIC16F877A Configuration Bit Settings
; CONFIG
; __config 0xFF32
;__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF

DATO EQU 0x24
NUM EQU 0x23
CON EQU 0X20
   ORG        0
    GOTO    INICIO

INICIO
    BSF    STATUS,RP0
    CLRF    TRISD ;SALIDA
    CLRF    TRISB ;SALIDA
	BSF   	TRISA,0; RA0 ENTRADA
	BSF	TRISA, 1 ;ENTRADA
	BSF	TRISA, 2 ;ENTRADA
	CLRF	TRISE

    CLRF    TRISC; SALIDA
    BSF    ADCON1,3 ;1
    BSF    ADCON1,2 ;1
    BSF    ADCON1,1 ;1
    BCF    ADCON1,0 ;0 1110-> RAO AN0 = ANALOGO
    BSF    ADCON1,6 ;FRECUENCIA OSCILADOR
    BCF    ADCON1,7 ;JUSTIFICACION IZQ
    BCF    STATUS,RP0
    BSF    ADCON0,7
    BCF    ADCON0,6
    BCF    ADCON0,5
    BCF    ADCON0,4
    BCF    ADCON0,3 ;CANAL AN0
    BSF    ADCON0,0 ;ADC ON
	BSF	TRISE, 0
	BSF	TRISE, 1
	BSF	TRISE, 2

;VARIABLE CON = 00000000
	MOVLW	B'00000001'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
START
    BSF    ADCON0,2;GO/DONE -> 1
ADC    BTFSC    ADCON0,2
    GOTO    ADC
    MOVF    ADRESH,W
    MOVWF    PORTD ;SALIDA DE PORTD MAS SIGNIFICATIVOS
    BSF    STATUS,RP0
    MOVF    ADRESL,W
    BCF    STATUS,RP0
    MOVWF    PORTC ;SALIDA DE PORTC MENOS SIGNIFICATIVOS

	CALL	Incrementico

	MOVLW	B'111'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	PORTE

	BTFSC	PORTA, 1
	GOTO	ENTRA
	GOTO	FIN
ENTRA
	BTFSC	CON, 0
	GOTO 	W1
	GOTO	W2
W1
	MOVLW	B'00000001'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
	GOTO 	FIN
W2
	BTFSC	CON, 1
	GOTO	W3
	MOVLW	B'00000011'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
	GOTO 	FIN
W3
	BTFSC	CON, 2
	GOTO	W4
	MOVLW	B'00000111'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
	GOTO 	FIN
W4
	BTFSC	PORTD, 3
	GOTO	W5
	MOVLW	B'00001111'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
	GOTO 	FIN
W5
	BTFSC	CON, 4
	GOTO	W6
	MOVLW	B'00011111'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
	GOTO 	FIN
W6
	BTFSS	CON, 5
	GOTO	W7
	MOVLW	B'00111111'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
	GOTO 	FIN
W7
	BTFSC	CON, 6
	GOTO	W8
	MOVLW	B'01111111'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
	GOTO 	FIN
W8
	BTFSC	CON, 7
	GOTO	W9
	MOVLW	B'11111111'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	PORTB
	GOTO 	FIN
W9
	BTFSC	CON, 6
	GOTO	W10
	MOVLW	B'01000000'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	PORTB
	GOTO 	FIN
W10
	BTFSC	PORTC, 7
	GOTO	LLENO
	MOVLW	B'11000000'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	CON
	GOTO 	FIN
LLENO
	MOVLW 	B'000'
FIN
	GOTO    START

;FUNCIONES
;C6 C7 D6 D7
Incrementico
	BTFSC	PORTC,6
	GOTO	Comprobar1
	BTFSC	PORTC,7
	GOTO	Comprobar1
	BTFSC	PORTD,6
	GOTO	Comprobar1
	BTFSC	PORTD,7
	GOTO	Comprobar1
	GOTO	Llamar0
Comprobar1
	BTFSC	PORTC,6
	GOTO	Comprobar2
	BTFSS	PORTC,7
	GOTO	Comprobar2
	BTFSC	PORTD,6
	GOTO	Comprobar2
	BTFSC	PORTD,7
	GOTO	Comprobar2
	GOTO	Llamar1
Comprobar2
	BTFSC	PORTC,6
	GOTO	Comprobar3
	BTFSC	PORTC,7
	GOTO	Comprobar3
	BTFSS	PORTD,6
	GOTO	Comprobar3
	BTFSC	PORTD,7
	GOTO	Comprobar3
	GOTO	Llamar2
Comprobar3
	BTFSS	PORTC,6
	GOTO	Comprobar4
	BTFSC	PORTC,7
	GOTO	Comprobar4
	BTFSS	PORTD,6
	GOTO	Comprobar4
	BTFSC	PORTD,7
	GOTO	Comprobar4
	GOTO	Llamar3

Comprobar4
	BTFSS	PORTC,6
	GOTO	Comprobar5
	BTFSS	PORTC,7
	GOTO	Comprobar5
	BTFSS	PORTD,6
	GOTO	Comprobar5
	BTFSC	PORTD,7
	GOTO	Comprobar5
	GOTO	Llamar4
Comprobar5
	BTFSS	PORTC,6
	GOTO	Comprobar6
	BTFSC	PORTC,7
	GOTO	Comprobar6
	BTFSC	PORTD,6
	GOTO	Comprobar6
	BTFSS	PORTD,7
	GOTO	Comprobar6
	GOTO	Llamar5
Comprobar6
	BTFSC	PORTC,6
	GOTO	Comprobar7
	BTFSS	PORTC,7
	GOTO	Comprobar7
	BTFSC	PORTD,6
	GOTO	Comprobar7
	BTFSS	PORTD,7
	GOTO	Comprobar7
	GOTO	Llamar6
Comprobar7
	BTFSC	PORTC,6
	GOTO	Comprobar8
	BTFSC	PORTC,7
	GOTO	Comprobar8
	BTFSS	PORTD,6
	GOTO	Comprobar8
	BTFSS	PORTD,7
	GOTO	Comprobar8
	GOTO	Llamar7
	;GOTO	BAJA
Comprobar8
	BTFSC	PORTC,6
	GOTO	Comprobar9
	BTFSS	PORTC,7
	GOTO	Comprobar9
	BTFSS	PORTD,6
	GOTO	Comprobar9
	BTFSS	PORTD,7
	GOTO	Comprobar9
	GOTO	LLamar8
	;GOTO 	NORMAL
Comprobar9
	BTFSS	PORTC,6
	GOTO	Terminar
	BTFSS	PORTC,7
	GOTO	Terminar
	BTFSS	PORTD,6
	GOTO	Terminar
	BTFSS	PORTD,7
	GOTO	Terminar
	GOTO	Llamar9

LLamar0
	CALL	NumerO0
	GOTO	Terminar
LLamar1
	CALL	Numero0
	GOTO	Terminar
LLamar2
	CALL	Numero0
	GOTO	Terminar
	GOTO	Terminar
Llamar3
	CALL	Numero0
	GOTO	Terminar
Llamar4
	CALL	Numero0
	GOTO	Terminar
Llamar5
	CALL	Numero0
	GOTO	Terminar
Llamar6
	CALL	Numero0
	GOTO	Terminar
Llamar7
	CALL	Numero0
	GOTO	Terminar
Llamar8
	CALL	Numero0
	GOTO	Terminar
Llamar9
	CALL	Numero9
	GOTO	Terminar

Numero0
	MOVLW	B'00110111'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	PORTB
	RETURN
Numero9
	MOVLW	B'00110001'
	MOVWF	NUM
	MOVF	NUM, W
	MOVWF	PORTB
	RETURN

Terminar
	RETURN