	ORG	0X00
CONFIGURACION
	BSF	STATUS, RP0
	CLRF	TRISD		; SALIDA
	BSF	TRISA, 0 	; RA0 ENTRADA
	BSF	TRISA, 1	; ENTRADA RECEPTOR
	BSF	TRISA, 2	; ENTRADA BOTON RESTA
	CLRF	TRISC 		; SALIDA
	CLRF	TRISB		; SALIDA
	CLRF	TRISE		; SALIDA
	BSF	ADCON1, 3
	BSF	ADCON1, 2
	BSF	ADCON1, 1
	BCF	ADCON1, 0 	; 1110 -> RA0 AN0 = ANALOGO
	BSF	ADCON1, 6	; FOSC/64
	BCF	ADCON1, 7 	; JUSTIFICACIÓN IZQUIERDA (MAS SIGINIFICATIVOS IZQUIERDA)
	BCF	STATUS, RP0
	BSF	ADCON0, 7
	BCF	ADCON0, 6 	; FOSC/64
	BCF	ADCON0, 5
	BCF	ADCON0, 4
	BCF	ADCON0, 3 	; CANAL AN0
	BSF	ADCON0, 0 	; ADC ON

START
	BTFSS	PORTA, 2	;BOTON PARA RESTAR ALGUIEN EN AFORO
	GOTO	CONTINUAR	;0
	CALL	DECREMENTAR	;1
CONTINUAR
	BTFSS	PORTA, 1	;SE HA DECTECTADO ALGUIEN EN EL RECEPTOR
	GOTO 	START	 ;0
	CALL	INCREMENTAR

	BSF	ADCON0, 2	; GO/DONE --> 1
ADC
	;BITS MAS SIGNIFICATIVOS MAS A LA IZQUIERDA - PORTD
	;BITS MENOS SIGNIFICATIVOS MAS A LA DERECHA (SOLO SON 2) -PORTC
	BTFSC	ADCON0, 2
	GOTO	ADC
	MOVF	ADRESH,W
	MOVWF	PORTD		;BITS MAS SIGNIFICATIVOS

	;SE HA COMENTADO YA QUE NO SE UTILIZARAN LOS BITS MENOS SIGNIFICATIVOS
	BSF	STATUS, RP0
	MOVF	ADRESL, W
	BCF	STATUS, RP0	;REGRESO AL BANCO 0
	;MOVWF	PORTC		;BITS MENOS SIGNIFICATIVOS

	;FOTO RESISTENCIA DE 4.9V Max y 0.9 Min
	;4.9V = 1003 y 0.9V = 184
	;912 = 4.45V => COVID
DISPLAY
	;SUBLW = (F - W)
	;SI LA RESTA = POSITIVA	,C=1 Z=0 F - W > 0
	;SI LA RESTA = CERO	,C=1 Z=1 F - W = 0
	;SI LA RESTA = NEGATIVA	,C=0 Z=1 F - W < 0
	;SI C = 1 -> F >= W
	MOVF	PORTD, W
	SUBLW	B'11101111'	;912  = 11 10
	BTFSS	STATUS, C
	GOTO	COVID	;0
	GOTO	NORMAL	;1
NORMAL
	MOVLW	B'00110111'
	MOVWF	PORTB
	GOTO 	FIN
COVID
	MOVLW	B'00111001'
	MOVWF	PORTB
	GOTO	FIN
FIN
	GOTO START

INCREMENTAR
	MOVF	PORTC, W
	ADDLW	B'00000001'
	MOVWF 	PORTC
	SUBLW	B'00001010'
	BTFSS	STATUS, C
	GOTO	MAL	;0
	GOTO	BIEN	;1
BIEN
	BSF	PORTE, 0 ;PORTE0 Indica que se puede pasar
	BCF	PORTE, 1 ;PORTE1 Se apaga por si no dejaba pasar
	GOTO	FIN2
MAL
	BSF	PORTE, 1
	BCF	PORTE, 0
FIN2
	RETURN

DECREMENTAR
	BTFSS	PORTE, 2
	GOTO	RESTAR	;0
	GOTO	FIN3	;1
RESTAR
	BCF	PORTE, 2
	DECFSZ	PORTC, 1
	GOTO	FIN3
	BSF	PORTE, 2 ;SI LA RESTA DA CERO ACTIVA ESTO PARA QUE NO PERMITA RESTAR DESPUES
FIN3
	RETURN

	END